lidofinance/csm-widget

- features/create-node-operator/share-limit-banner/share-limit-banner.tsx
- shared/hooks/useCSMShareLimitInfo.ts
- CSM exhausted limit banner [CS-619](https://linear.app/lidofi/issue/CS-619/add-a-warning-if-queued-keys-active-keys-stake-share-limit)
> fix: exhausted limit with queued keys

- features/dashboard/bond/last-rewards.tsx
- shared/hooks/useLastRewardsFrame.ts
- plural forms for days to the Report
> hotfix: plural form

- features/add-keys/add-keys/add-keys-form.tsx
- features/create-node-operator/submit-keys-form/submit-keys-form.tsx
- features/view-keys/deposit-queue/deposit-queue-graph.tsx
- features/view-keys/deposit-queue/deposit-queue.tsx
- features/view-keys/deposit-queue/hover-provider.tsx
- features/view-keys/deposit-queue/index.ts
- features/view-keys/deposit-queue/legend.tsx
- features/view-keys/deposit-queue/part.tsx
- features/view-keys/deposit-queue/style.ts
- features/view-keys/deposit-queue/types.ts
- features/view-keys/deposit-queue/use-deposit-queue-graph.ts
- features/view-keys/view-keys-section/styles.tsx
- features/view-keys/view-keys.tsx
- shared/components/extra-width/extra-width.tsx
- shared/components/extra-width/index.ts
- shared/components/index.ts
- shared/hooks/index.ts
- shared/hooks/useCSMQueueBatches.ts
- shared/hooks/useCSMShareLimitInfo.ts
- View deposit queue [CS-587](https://linear.app/lidofi/issue/CS-587/add-deposit-queue-visualization)
- with your keys in queue
> feat: deposit queue + your batches

- package.json
- yarn.lock
- update matomo script to 0.51.0
> chore: udpate matomo to 0.51.0

- shared/hooks/use-permit-or-approve.ts
- fix use correct token for approve [CS-676](https://linear.app/lidofi/issue/CS-676/%5Bbug%5D)
> fix: correct token approval logic for STETH and WSTETH

- features/welcome/holesky-banner/holesky-banner.tsx
- features/welcome/holesky-banner/index.ts
- features/welcome/holesky-page.tsx
- features/welcome/maintenance-banner/maintenance-banner.tsx
- lib/getProps.ts
- pages/index.tsx
- shared/components/banner/styles.ts
> chore: add Holesky banner

- features/surveys/survey-setup/survey-setup.tsx
- features/surveys/survey-setup/transform.tsx
- features/surveys/types.ts
- setup survey: country is optional [CS-689](https://linear.app/lidofi/issue/CS-689/make-a-fields-with-country-optional-for-filling-in)
> chore: optional country fields in setup survey

- consts/external-links.ts
- shared/hooks/use-external-links.ts
- shared/transaction-modal/tx-stages-parts/after-keys-upload.tsx
- fix: hide beaconcha.in links on Hoodi (till it doesn't support Hoodi)
> fix: hide beaconcha.in on hoodi

- features/dashboard/bond/last-rewards.tsx
- shared/hooks/useLastRewardsReport.ts
> sync main to develop

- shared/hooks/use-surveys-call.ts
- disable Surveys banner for Hoodi
> chore: hoodi disable surveys banner

- features/claim-bond/claim-bond-form/claim-bond-form-info.tsx
- features/claim-bond/claim-bond-form/controls/source-select.tsx
- features/dashboard/bond/available-to-claim.tsx
- features/dashboard/bond/bond-balance.tsx
- features/dashboard/bond/last-rewards.tsx
- features/remove-keys/remove-keys/remove-keys-form-info.tsx
- features/surveys/surveys-home/surverys-home.tsx
- features/unlock-bond/unlock-bond-form/controls/info.tsx
- shared/components/titled-selectable-amount/titled-selectable-amount.tsx
- improve toolitps on Claim bond tab [CS-573](https://linear.app/lidofi/issue/CS-573/add-tooltips-for-excess-and-insufficient-bond)
> chore: claim bond tooltips

- consts/external-links.ts
- features/dashboard/dashboard.tsx
- features/dashboard/external/external-section.tsx
- features/dashboard/external/use-external-button.tsx
- shared/hooks/use-external-links.ts
- show external dashboards for Hoodi (beaconcha & operators widget)
> chore: hoodi external dashboards

- features/add-keys/add-keys/context/use-add-keys-submit.ts
- after upload keys -> redirect to view keys tab [CS-541](https://linear.app/lidofi/issue/CS-541/after-uploading-keys-redirect-to-view-keys-tab)
> feat: redirect to keys view after add keys

- features/remove-keys/remove-keys/controls/keys-selector.tsx
- hide note about keys selecting if keys < 3 [CS-572](https://linear.app/lidofi/issue/CS-572/remove-the-note-about-sequential-array-if-keys-count-3)
> chore: hide note if keys < 3

- shared/wallet/wallet-modal/wallet-modal.tsx
> fix: disconnect fail

- .github/workflows/tests.yml
- tests/widget/welcomePage.spec.ts
- Unskip tests after deploying new testnet with data-id attr in some elements.
- Remove CI Test trigger by pull_request
- Added schedule run
- Set up Discord notifications only for schedule run
> fix: unskip tests

- providers/inpage-navigation.tsx
- shared/layout/header/styles.tsx
- shared/node-operator/descriptor/styles.tsx
- shared/node-operator/switch-modal/styles.tsx
- styles/global.ts
- utils/scroll.ts
- sticky header on large and small screens
- fix jumping content on scroll appear
> chore: sticky header

- consts/external-links.ts
- add "Fees monitoring" external dashboard for Hoodi testnet
> chore: add fees monitoring external dashboard for hoodi testnet

- shared/hooks/use-initial-loading.ts
fix: stuck with infinite loading screen
> fix: stuck loading screen

- faq/hoodi/keys-7.md
- faq/mainnet/keys-7.md
- update FAQ: value of removal fee [CS-751](https://linear.app/lidofi/issue/CS-751/update-faq-change-removal-fee-amount)
> chore: udpate FAQ - value of removal fee

- features/add-bond/add-bond-form/context/use-add-bond-submit.ts
- features/add-keys/add-keys/context/use-add-keys-submit.ts
- features/change-role/change-role-form/context/use-change-role-submit.ts
- features/claim-bond/claim-bond-form/context/use-claim-bond-submit.ts
- features/claim-type/claim-type-form/context/use-claim-type-submit.ts
- features/eject-keys/eject-keys/context/use-eject-keys-submit.ts
- features/normalize-queue/normalize-queue-form/context/use-normalize-queue-submit.ts
- features/remove-keys/remove-keys/context/use-remove-keys-submit.ts
- features/stealing/stealing-cancel-form/context/use-stealing-cancel-submit.ts
- features/stealing/stealing-report-form/context/use-stealing-report-submit.ts
- features/transfer-keys/transfer-keys/context/use-transfer-keys-submit.ts
- features/unlock-bond/unlock-bond-form/context/use-unlock-bond-submit.ts
- fix invariant for nodeOperatorId
> fix: invariant operator id 0

- features/dashboard/bond/last-rewards.tsx
- package.json
- shared/layout/header/dummy-header.tsx
- shared/layout/header/feedback-line.tsx
- shared/layout/header/header.tsx
- shared/layout/header/semi-dummy-header.tsx
- shared/layout/header/styles.tsx
- yarn.lock
- fix: hide rewards threshold after rewards v2
- fix: feedback line mobile view
> fix: rewards treshold

- features/add-bond/add-bond-form/context/use-add-bond-submit.ts
- features/add-keys/add-keys/context/use-add-keys-submit.ts
- features/create-node-operator/submit-keys-form/context/use-submit-keys-submit.ts
- features/eject-keys/eject-keys/context/use-eject-keys-submit.ts
- features/monitoring/strikes-section/last-strike.tsx
- features/monitoring/strikes-section/strikes-section.tsx
- features/monitoring/strikes-section/styles.ts
- features/stealing/stealing-cancel-form/context/use-stealing-cancel-submit.ts
- features/stealing/stealing-report-form/context/use-stealing-report-submit.ts
- features/unlock-bond/unlock-bond-form/context/use-unlock-bond-submit.ts
- features/view-keys/view-keys-section/strikes-counts.tsx
- features/view-keys/view-keys-section/styles.tsx
- package.json
- shared/components/index.ts
- shared/components/key-strikes/index.ts
- shared/components/key-strikes/key-strikes.tsx
- shared/components/key-strikes/styles.ts
- yarn.lock
- fix: rewards share
- fix: add keys covered by excess bond
- chore: move key-strikes component to shared components
> fix: rewards share, add keys with excess bond

- features/dashboard/keys/keys-section.tsx
- features/monitoring/strikes-section/last-strike.tsx
- features/monitoring/strikes-section/strikes-section.tsx
- features/view-keys/view-keys-section/strikes-counts.tsx
- package.json
- shared/components/faq/faq-bond-amount.tsx
- shared/components/faq/faq-strike-lifetime.tsx
- shared/components/faq/faq-strike-threshold.tsx
- shared/components/faq/index.ts
- shared/components/status-chip/status-chip.tsx
- shared/components/status-comment/comments.tsx
- shared/components/status-comment/status-comment.tsx
- yarn.lock
- fix: last strike tooltip for keys table
> fix: strikes tooltip to keys table

- features/eject-keys/eject-keys/form-loading.tsx
- features/remove-keys/remove-keys/context/use-remove-keys-form-network-data.tsx
- fix: remove unchecked and non_queued keys
> fix: remove unchecked and non_queued keys

- config/groups/web3.ts
- modules/web3/web3-provider/lido-sdk.tsx
- set limit for block range for eth_getLogs (1M)
> fix: set block range limit (1M)

- features/starter-pack/banner-operator-custom-addresses/use-operator-custom-addresses.ts
- modules/web3/operator-provider/use-cached-id.ts
- shared/hooks/use-local-storage.ts
- shared/hooks/use-session-storage.ts
- utils/index.ts
- utils/scroll.ts
- utils/serialize-bigint.ts
- fix: localStorage and sessionStorage hooks getting better
> fix: storage hooks

- features/claim-type/claim-type-page.tsx
- features/ics/apply-form/context/use-modal-stages.tsx
- features/ics/apply-form/controls/additional-addresses.tsx
- features/ics/form-status/components/status-header.tsx
- features/ics/ics-apply-page.tsx
- features/ics/ics-scores-page.tsx
- features/ics/round-banner/index.ts
- features/ics/round-banner/round-banner.tsx
- features/ics/round-banner/styles.tsx
- features/ics/score-system/application-flow.tsx
- features/ics/shared/consts.tsx
- features/ics/shared/index.ts
- features/ics/shared/score-data.tsx
[CS-838](https://linear.app/lidofi/issue/CS-838/add-banner-to-ics-ui-change-wording)
- add links in score-system page
- add banner about start assessed date
- fix test on status page
> chore: add links, update texts

- config/feature-flags/types.ts
- config/feature-flags/utils.ts
- pages/type/ics-apply.tsx
- pages/type/ics-system.tsx
- providers/modify-provider.tsx
- shared/hooks/use-show-rule.ts
- shared/layout/navigation/use-nav-items.tsx
- shared/navigate/switcher/type-page-switcher.tsx
> feat: enable ics

- features/ics/form-status/components/status-header.tsx
Update ICS Approved text to account for the fact that CSM v2 is not yet live
I've never tested it
> fix: Update ICS Approved text

- features/ics/shared/score-data.tsx
> chore: ics: update text for participating in votes

- config/feature-flags/types.ts
- config/feature-flags/utils.ts
- consts/urls.ts
- features/surveys/surveys-home-page.tsx
- features/surveys/surveys-home/surverys-home.tsx
- modules/web3/hooks/use-invites.ts
- modules/web3/web3-provider/lido-sdk.tsx
- package.json
- pages/surveys/[[...slug]].tsx
- providers/modify-provider.tsx
- shared/hook-form/deposit-data/deposit-data-parsed.tsx
- shared/hooks/use-show-rule.ts
- shared/hooks/use-survey-enabled.ts
- shared/layout/header/feedback-line.tsx
- shared/navigate/redirection-map.ts
- shared/navigate/use-correct-path.ts
- utilsApi/api/validation.ts
- utilsApi/contractAddressesMetricsMap.ts
- yarn.lock
- fixes before release
- fix: double click on remove key button in deposit data
- fix: Operators Type: open claim ICS if it's available
- hide surveys on testnet (available by `?survey-setup=1` url)
> chore: prepare to release
